### PR TITLE
feat: [REVER-51] Workable Integration

### LINKED ISSUE #551: [REVER-51] Workable Integration
<p>To goal of this issue is to support Workable as an integration within Revert APIs.</p><p>Workable documentation: <a target="_blank" rel="noopener noreferrer nofollow" class="text-custom-primary-300 underline underline-offset-[3px] hover:text-custom-primary-500 transition-colors cursor-pointer" href="https://workable.readme.io/reference/generate-an-access-token">https://workable.readme.io/reference/generate-an-access-token</a></p><p><strong>Next steps:</strong></p><ul class="list-disc pl-7 space-y-2"><li class="not-prose space-y-2"><p>Familiarise yourself with the <strong>Workable</strong> APIs</p></li><li class="not-prose space-y-2"><p>Understand how we store OAuth credentials within Revert and make changes such that we can allow our users to be able to make a <code class="rounded bg-custom-background-80 px-1 py-[2px] font-mono font-medium text-orange-500 border-[0.5px] border-custom-border-200 text-sm" spellcheck="false">connection</code> with a Workable account</p></li></ul><p>As us any questions you might have on our <a target="_blank" rel="nofollow" class="text-custom-primary-300 underline underline-offset-[3px] hover:text-custom-primary-500 transition-colors cursor-pointer" href="https://discord.com/invite/q5K5cRhymW"><u>discord</u></a>.</p>

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
### Description

workable integration
oauth+refresh
services-job ,candidates ,offer ,department
dcumentation

Fixes #551 

Things remaining: mergeConflicts,testing,documentation,seed.ts,field.ts,fern completion,preprocessing(if required),permissions + any other error that shows up.

### Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

### How Has This Been Tested?

postman

### Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by rajeshj11** [comment]
@manish-singh-bisht Did you get the client_id and client_secret from workable account. if yes, How did you get it?

**Comment by rajeshj11** [comment]
I did implement similar changes in my local. However, due to testing, I
have not proceeded further.

**Comment by rajeshj11** [comment]
I am blocked by that client_id and client_sceret. I did reach workable
support. It is a dead end for me. So I stopped working on it. I saw your PR
changes, thought you got that info from Workable, and want to know where I
lagged.

**Comment by Nabhag8848** [comment]
Closing for now, as no workable api access.

**Pull request closed without merging**
