### PR TITLE
feat: added bitbucket issue integration

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
### Description
- bitbucket issue integration.
- added task,user,comment,collection endpoints.
- added oauth flow.

### Fixes
- #301

### Type of change

-   [x] New feature (non-breaking change which adds functionality)
-  [x] This change requires a documentation update

### How Has This Been Tested?
Postman

Demo: https://github.com/revertinc/revert/pull/507#issuecomment-1984232241

> all endpoint are tested
> 
> full video oauth ,task,user,comment,collection
> 
> https://www.loom.com/share/5d0b0526b03c450da1e5a22af2ec9c7f

### Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by manish-singh-bisht** [comment]
pr is ready for review.

Need to change the images link though.

**Comment by jatinsandilya** [comment]
@manish-singh-bisht Thanks for the PR 🙏🏼  

Before I look into it - 

Could you please add a loom demo-ing the integration? Also use the PR template for the description of this PR with the relevant issue that it closes?

**Comment by manish-singh-bisht** [comment]
here https://www.loom.com/share/920cf29e485343f4a74213115b0da5cc

**Comment by jatinsandilya** [comment]
> here https://www.loom.com/share/920cf29e485343f4a74213115b0da5cc

Thanks for this @manish-singh-bisht! Could you update or add a loom to show the APIs being tested using Postman for each of the endpoints you have added?

**Comment by manish-singh-bisht** [comment]
here users,comment ,task was previously done
collections is remaining
https://www.loom.com/share/85d5fd05685c413fb0ee06d9f1b9bfb9

**Comment by manish-singh-bisht** [comment]
collections endpoint

https://www.loom.com/share/16a953951f234898a3ed29b4a73b05de

**Comment by manish-singh-bisht** [comment]
all endpoint are tested  

full video oauth ,task,user,comment,collection 

https://www.loom.com/share/5d0b0526b03c450da1e5a22af2ec9c7f

**Review by jatinsandilya — APPROVED** [review]
LGTM, thanks for contribution @manish-singh-bisht 🎉

**Pull request merged**
